let library = [
    { name: 'To Kill a Mockingbird', author: 'Harper Lee', price: '9.99', section: 'Popular', category: 'Classic Literature', availability: true, category: 'smth', imageUrl: '../Imgs/Books/ (1).jpg' },
    { name: '1984', author: 'George Orwell', price: '14.99', section: 'Sales', category: 'Dystopian', availability: false, imageUrl: '../Imgs/Books/ (2).jpg' },
    { name: 'Pride and Prejudice', author: 'Jane Austen', price: '12.99', section: 'Most_read', category: 'Classic Romance', availability: true, imageUrl: '../Imgs/Books/ (3).jpg' },
    { name: 'To Kill a Mockingbird', author: 'Harper Lee', price: '9.99', section: 'Popular', category: 'Classic', availability: true, imageUrl: '../Imgs/Books/ (1).jpg' },
    { name: '1984', author: 'George Orwell', price: '14.99', section: 'Sales', category: 'Dystopian', availability: false, imageUrl: '../Imgs/Books/ (2).jpg' },
    { name: 'Pride and Prejudice', author: 'Jane Austen', price: '12.99', section: 'Most_read', category: 'Classic Romance', availability: true, imageUrl: '../Imgs/Books/ (3).jpg' },
    { name: 'The Great Gatsby', author: 'F. Scott Fitzgerald', price: '15.99', section: 'Popular', category: 'Classic', availability: false, imageUrl: '../Imgs/Books/ (4).jpg' },
    { name: 'Catcher in the Rye', author: 'J.D. Salinger', price: '11.99', section: 'Sales', category: 'Literary Fiction', availability: true, imageUrl: '../Imgs/Books/ (5).jpg' },
    { name: 'The Hobbit', author: 'J.R.R. Tolkien', price: '10.99', section: 'Most_read', category: 'Fantasy', availability: false, imageUrl: '../Imgs/Books/ (6).jpg' },
    { name: 'The Alchemist', author: 'Paulo Coelho', price: '18.99', section: 'Popular', category: 'Philosophical Fiction', availability: true, imageUrl: '../Imgs/Books/ (7).jpg' },
    { name: 'The Little Prince', author: 'Antoine de Saint-Exupéry', price: '16.99', section: 'Sales', category: 'Children\'s Literature', availability: false, imageUrl: '../Imgs/Books/ (8).jpg' },
    { name: 'Wuthering Heights', author: 'Emily Brontë', price: '13.99', section: 'Most_read', category: 'Classic Fiction', availability: true, imageUrl: '../Imgs/Books/ (9).jpg' },
    { name: 'Jane Eyre', author: 'Charlotte Brontë', price: '17.99', section: 'Popular', category: 'Gothic Fiction', availability: false, imageUrl: '../Imgs/Books/ (10).jpg' },
    { name: 'Crime and Punishment', author: 'Fyodor Dostoevsky', price: '15.99', section: 'None', category: 'Philosophical Novel', availability: true, imageUrl: '../Imgs/Books/ (34).jpg' },
    { name: 'The Picture of Dorian Gray', author: 'Oscar Wilde', price: '16.99', section: 'None', category: 'Gothic', availability: false, imageUrl: '../Imgs/Books/ (35).jpg' },
    { name: 'The Great Gatsby', author: 'F. Scott Fitzgerald', price: '10.99', section: 'Popular', category: 'Classic Literature', availability: true, imageUrl: '../Imgs/Books/ (4).jpg' },
    { name: 'War and Peace', author: 'Leo Tolstoy', price: '13.99', section: 'Sales', category: 'Historical Fiction', availability: false, imageUrl: '../Imgs/Books/ (5).jpg' },
    { name: 'Anna Karenina', author: 'Leo Tolstoy', price: '18.99', section: 'Most_read', category: 'Literary Fiction', availability: true, imageUrl: '../Imgs/Books/ (6).jpg' },
    { name: 'The Catcher in the Rye', author: 'J.D. Salinger', price: '11.99', section: 'Popular', category: 'Literary Fiction', availability: false, imageUrl: '../Imgs/Books/ (7).jpg' },
    { name: 'The Brothers Karamazov', author: 'Fyodor Dostoevsky', price: '20.99', section: 'Sales', category: 'Philosophical Novel', availability: true, imageUrl: '../Imgs/Books/ (8).jpg' },
    { name: 'Crime and Punishment', author: 'Fyodor Dostoevsky', price: '15.99', section: 'None', category: 'Philosophical Novel', availability: true, imageUrl: '../Imgs/Books/ (34).jpg' },
    { name: 'The Picture of Dorian Gray', author: 'Oscar Wilde', price: '16.99', section: 'None', category: 'Gothic', availability: false, imageUrl: '../Imgs/Books/ (35).jpg' },
];
