export const library = [
  {
    section: "Popular",
    name: "The Art Of War",
    price: "$29.99",
    imageUrl: "../Imgs/Books/ (1).jpg",
    author: "Sun Tzu",
    category: "Military",
    availability: true,
    description:
      "This ancient Chinese military treatise offers profound insights into strategy, tactics, and warfare philosophy, emphasizing the importance of adaptability and psychological warfare.",
  },
  {
    section: "Popular",
    name: "Master Techniques in Surgery",
    price: "$12.99",
    imageUrl: "../Imgs/Books/ (2).jpg",
    author: "Various Authors",
    category: "Medical",
    availability: false,
    description:
      "This collection provides detailed, expert guidance on advanced surgical techniques across various specialties, serving as an indispensable resource for experienced surgeons.",
  },
  {
    section: "Popular",
    name: "The Banker's Wife",
    price: "$29.99",
    imageUrl: "../Imgs/Books/ (3).jpg",
    author: "Cristina Alger",
    category: "Thriller",
    availability: true,
    description:
      "A gripping thriller that delves into the secretive world of offshore banking. After her husband's mysterious plane crash, a woman uncovers financial conspiracies.",
  },
  {
    section: "Popular",
    name: "The Edge of the Sea",
    price: "$29.99",
    imageUrl: "../Imgs/Books/ (4).jpg",
    author: "Rachel Carson",
    category: "Science",
    availability: false,
    description:
      "Carson presents a natural and detailed exploration of the coastal ecosystems of America, combining scientific insight with poetic prose to celebrate marine biodiversity.",
  },
  {
    section: "Popular",
    name: "The Subtle Art of not giving a fuck",
    price: "$19.99",
    imageUrl: "../Imgs/Books/ (5).jpg",
    author: "Mark Manson",
    category: "Self Help",
    availability: true,
    description:
      "In this irreverent and straightforward self-help book, Manson challenges conventional wisdom with sharp humor, advocating for a more selective approach to life's challenges.",
  },
  {
    section: "Popular",
    name: "The Ebb Tide",
    price: "$44.99",
    imageUrl: "../Imgs/Books/ (6).jpg",
    author: "Beverly Lewis",
    category: "Fiction",
    availability: false,
    description:
      "This novel explores the journey of an Amish woman who questions her path in life during a summer away from her community, sparking self-discovery.",
  },
  {
    section: "Popular",
    name: "On the way to the Wedding",
    price: "$18.99",
    imageUrl: "../Imgs/Books/ (7).jpg",
    author: "Julia Quinn",
    category: "Romance",
    availability: true,
    description:
      "A charming and romantic tale from the Bridgerton series, this story weaves the complexities of love and decisions leading up to a dramatic wedding.",
  },
  {
    section: "Popular",
    name: "Jets!Jets!Jets!",
    price: "$29.99",
    imageUrl: "../Imgs/Books/ (8).jpg",
    author: "Peter March",
    category: "Technology",
    availability: false,
    description:
      "An enthusiastic exploration of military and civilian jet aircraft, detailing their development, technology, and impact on modern aviation.",
  },
  {
    section: "Popular",
    name: "Libraries of The Future",
    price: "$19.99",
    imageUrl: "../Imgs/Books/ (9).jpg",
    author: "Leland M. Smith",
    category: "Technology",
    availability: true,
    description:
      "This book predicts the evolution of libraries, examining how technological advancements will transform data storage, retrieval, and the role of librarians.",
  },
  {
    section: "Popular",
    name: "Elon Musk",
    price: "$19.99",
    imageUrl: "../Imgs/Books/ (10).jpg",
    author: "Ashlee Vance",
    category: "Biography",
    availability: false,
    description:
      "A biography providing an in-depth look at the entrepreneur who founded SpaceX, Tesla, and SolarCity, driven by his vision of a technologically advanced future.",
  },
  {
    section: "Popular",
    name: "Lord of the Flies",
    price: "$29.99",
    imageUrl: "../Imgs/Books/ (11).jpg",
    author: "William Golding",
    category: "Fiction",
    availability: true,
    description:
      "A profound novel that explores the descent into savagery of a group of British boys stranded on an uninhabited island, highlighting the inherent violence in human nature.",
  },
  {
    section: "Popular",
    name: "The Leaf",
    price: "$19.99",
    imageUrl: "../Imgs/Books/ (12).jpg",
    author: "J.R.R. Tolkien",
    category: "Fiction",
    availability: false,
    description:
      "A short story by J.R.R. Tolkien about a painter who is obsessed with creating a perfect leaf, illustrating themes of creativity and legacy.",
  },
  {
    section: "Popular",
    name: "The secret Language Of Birthdays",
    price: "$39.99",
    imageUrl: "../Imgs/Books/ (13).jpg",
    author: "Gary Goldschneider",
    category: "Science",
    availability: true,
    description:
      "This book offers detailed personality profiles based on astrology and psychology, providing insights into each day of the year and its astrological significance.",
  },
  {
    section: "Popular",
    name: "Red White Royal Blue",
    price: "$29.99",
    imageUrl: "../Imgs/Books/ (14).jpg",
    author: "Casey McQuiston",
    category: "Romance",
    availability: false,
    description:
      "A fresh, energetic story of a romance between the First Son of the United States and the Prince of Wales, exploring themes of identity and duty.",
  },
  {
    section: "Popular",
    name: "Game Of Thrones",
    price: "$25.99",
    imageUrl: "../Imgs/Books/ (15).jpg",
    author: "George R. R. Martin",
    category: "Fantasy",
    availability: true,
    description:
      "The first book in the 'A Song of Ice and Fire' series, this epic fantasy novel is filled with intrigue, betrayal, and supernatural elements in a medieval setting.",
  },
  {
    section: "Popular",
    name: "Nothing",
    price: "$10.99",
    imageUrl: "../Imgs/Books/ (16).jpg",
    author: "Janne Teller",
    category: "Philosophical Fiction",
    availability: false,
    description:
      "A provocative novel about a group of teenagers who start questioning the meaning of life and decide to give up valued possessions to find answers.",
  },
  {
    section: "Popular",
    name: "Snapdragon",
    price: "$9.99",
    imageUrl: "../Imgs/Books/ (17).jpg",
    author: "Kat Leyh",
    category: "Graphic Novel",
    availability: true,
    description:
      "This graphic novel follows a young girl who befriends a local witch. They explore themes of identity, friendship, and the acceptance of one’s true self.",
  },
  {
    section: "Popular",
    name: "Working On Mars",
    price: "$39.99",
    imageUrl: "../Imgs/Books/ (18).jpg",
    author: "William K. Hartmann",
    category: "Science",
    availability: false,
    description:
      "This scientific book explores the practical aspects and challenges of human operations on Mars, based on real-life missions and future colonization plans.",
  },
  {
    section: "Popular",
    name: "Harry Potter",
    price: "$4.99",
    imageUrl: "../Imgs/Books/ (19).jpg",
    author: "J.K. Rowling",
    category: "Fantasy",
    availability: true,
    description:
      "The first novel in the iconic fantasy series, introducing young Harry Potter and his magical adventures at Hogwarts School of Witchcraft and Wizardry.",
  },
  {
    section: "Sale",
    name: "The Duke and I",
    price: "$30.99",
    imageUrl: "../Imgs/Books/ (20).jpg",
    author: "Julia Quinn",
    category: "Romance",
    availability: false,
    description:
      "A historical romance set in Regency England, this novel follows the blossoming romance between Simon Basset and the clever, kind Daphne Bridgerton.",
  },
  {
    section: "Sale",
    name: "Historia Czasu",
    price: "$49.99",
    imageUrl: "../Imgs/Books/ (21).jpg",
    author: "Stephen Hawking",
    category: "Science",
    availability: true,
    description:
      "An exploration of the cosmos, from the Big Bang to black holes, explaining complex scientific concepts in clear, accessible language.",
  },
  {
    section: "Sale",
    name: "Nothing Part.2",
    price: "$35.99",
    imageUrl: "../Imgs/Books/ (22).jpg",
    author: "Janne Teller",
    category: "Philosophical Fiction",
    availability: false,
    description:
      "A sequel that delves deeper into existential themes, exploring the meaning of life through a dramatic and thought-provoking narrative.",
  },
  {
    section: "Sale",
    name: "Artie And The WolfMoon",
    price: "$17.99",
    imageUrl: "../Imgs/Books/ (23).jpg",
    author: "Olivia Stephens",
    category: "Graphic Novel",
    availability: true,
    description:
      "A beautifully illustrated graphic novel that combines elements of family secrets, supernatural beings, and self-discovery through the adventures of Artie and her family.",
  },
  {
    section: "Sale",
    name: "Read People Like A Book",
    price: "$3.99",
    imageUrl: "../Imgs/Books/ (24).jpg",
    author: "Patrick King",
    category: "Medical",
    availability: false,
    description:
      "Offers techniques and insights on how to analyze people effectively, enhancing interpersonal communication and understanding through psychological principles.",
  },
  {
    section: "Sale",
    name: "Control Your Mind",
    price: "$4.99",
    imageUrl: "../Imgs/Books/ (25).jpg",
    author: "Various Authors",
    category: "Self Help",
    availability: true,
    description:
      "A compilation of expert advice on mastering your thoughts and emotions to enhance your daily life and achieve personal goals.",
  },
  {
    section: "Sale",
    name: "Landing Beaches",
    price: "$19.99",
    imageUrl: "../Imgs/Books/ (27).jpg",
    author: "George Forty",
    category: "History",
    availability: false,
    description:
      "A detailed historical account of the D-Day landings, providing insights into the planning, execution, and impact of this pivotal WWII event.",
  },
  {
    section: "Sale",
    name: "Fifty Shades Of Grey",
    price: "$29.99",
    imageUrl: "../Imgs/Books/ (28).jpg",
    author: "E.L. James",
    category: "Romance",
    availability: true,
    description:
      "An erotic romance that explores the deepening relationship between a college graduate, Anastasia Steele, and a young business magnate, Christian Grey.",
  },
  {
    section: "Sale",
    name: "Romancing Mister Bridgerton",
    price: "$19.99",
    imageUrl: "../Imgs/Books/ (29).jpg",
    author: "Julia Quinn",
    category: "Romance",
    availability: false,
    description:
      "Part of the Bridgerton series, this romance novel follows Penelope Featherington and her unrequited love for Colin Bridgerton, with secrets and love unfolding.",
  },
  {
    section: "Sale",
    name: "Don't Believe Everything You Think",
    price: "$14.99",
    imageUrl: "../Imgs/Books/ (30).jpg",
    author: "Joseph Nguyen",
    category: "Self Help",
    availability: true,
    description:
      "This self-help book provides strategies to challenge and overcome negative thinking patterns that prevent personal growth and happiness.",
  },
  {
    section: "Sale",
    name: "Encounter At Alpenrose",
    price: "$23.99",
    imageUrl: "../Imgs/Books/ (31).jpg",
    author: "Anonymous",
    category: "Fiction",
    availability: false,
    description:
      "A mysterious and engaging fiction novel that intertwines romance and intrigue in a captivating mountain setting.",
  },
  {
    section: "Sale",
    name: "A Sir Philip con amor",
    price: "$27.99",
    imageUrl: "../Imgs/Books/ (32).jpg",
    author: "Julia Quinn",
    category: "Romance",
    availability: true,
    description:
      "This romance novel focuses on Eloise Bridgerton's journey of unexpected love with Sir Philip Crane, blending emotional depth with historical romance.",
  },
  {
    section: "Sale",
    name: "Yours Truly",
    price: "$16.99",
    imageUrl: "../Imgs/Books/ (33).jpg",
    author: "Kirsty Greenwood",
    category: "Romance",
    availability: false,
    description:
      "A fun, romantic comedy that tells the story of Natalie Butterworth, who accidentally gains the ability to say exactly what's on her mind.",
  },
  {
    section: "Sale",
    name: "Ansiedade",
    price: "$32.99",
    imageUrl: "../Imgs/Books/ (34).jpg",
    author: "Augusto Cury",
    category: "Self Help",
    availability: true,
    description:
      "Discusses the impact of anxiety on mental health and offers practical methods and techniques to manage and reduce anxiety in daily life.",
  },
  {
    section: "Sale",
    name: "Jee Main",
    price: "$12.99",
    imageUrl: "../Imgs/Books/ (35).jpg",
    author: "Various Authors",
    category: "Educational",
    availability: false,
    description:
      "A comprehensive guide for students preparing for the Joint Entrance Examination Main, covering key subjects, exam strategies, and practice questions.",
  },
  {
    section: "Sale",
    name: "Introduction To Google Analytics",
    price: "$12.99",
    imageUrl: "../Imgs/Books/ (38).jpg",
    author: "Justin Cutroni",
    category: "Technology",
    availability: true,
    description:
      "A practical guide to understanding and using Google Analytics to gather and analyze data about website traffic and improve digital marketing strategies.",
  },
  {
    section: "Most Read",
    name: "A Gentle Reminder",
    price: "$19.99",
    imageUrl: "../Imgs/Books/ (39).jpg",
    author: "Bianca Sparacino",
    category: "Poetry",
    availability: true,
    description:
      "A collection of poetry and prose that offers solace, encouraging self-love and healing by reflecting on personal experiences and emotions.",
  },
  {
    section: "Most Read",
    name: "Emperor Of Rome",
    price: "$25.99",
    imageUrl: "../Imgs/Books/ (40).jpg",
    author: "Robert Fabbri",
    category: "History",
    availability: false,
    description:
      "A gripping tale in a series that vividly recounts the rise and reign of Emperor Vespasian, infusing historical events with drama and action.",
  },
  {
    section: "Most Read",
    name: "Castle in Corsica",
    price: "$15.99",
    imageUrl: "../Imgs/Books/ (41).jpg",
    author: "Margery Sharp",
    category: "Fiction",
    availability: true,
    description:
      "A delightful and witty novel about an unexpected inheritance that leads to adventures and misadventures in the picturesque setting of Corsica.",
  },
  {
    section: "Most Read",
    name: "Stop Pretending",
    price: "$19.99",
    imageUrl: "../Imgs/Books/ (42).jpg",
    author: "Sonya Sones",
    category: "Poetry",
    availability: false,
    description:
      "A poignant young adult novel in verse, exploring the emotional turmoil and recovery of a family dealing with mental illness.",
  },
  {
    section: "Most Read",
    name: "Nothing Part.3",
    price: "$0.99",
    imageUrl: "../Imgs/Books/ (43).jpg",
    author: "Janne Teller",
    category: "Philosophical Fiction",
    availability: true,
    description:
      "Continuing the existential exploration, this sequel deepens the philosophical quest for meaning in a stark, provocative narrative style.",
  },
  {
    section: "Most Read",
    name: "The Highest Dream",
    price: "$28.99",
    imageUrl: "../Imgs/Books/ (44).jpg",
    author: "Monica Sanz",
    category: "Romance",
    availability: false,
    description:
      "A romantic story about chasing dreams and overcoming obstacles, set against the backdrop of high societal expectations and personal desires.",
  },
  {
    section: "Most Read",
    name: "Psycho Cybernetics",
    price: "$9.99",
    imageUrl: "../Imgs/Books/ (45).jpg",
    author: "Maxwell Maltz",
    category: "Self Help",
    availability: true,
    description:
      "A romantic story about chasing dreams and overcoming obstacles, set against the backdrop of high societal expectations and personal desires.",
  },
  {
    section: "Most Read",
    name: "Skye Cameron",
    price: "$9.99",
    imageUrl: "../Imgs/Books/ (46).jpg",
    author: "Phyllis A. Whitney",
    category: "Romance",
    availability: false,
    description:
      "An intriguing romance novel with elements of mystery and suspense, set in the lush landscapes of Louisiana.",
  },
  {
    section: "Most Read",
    name: "Iris Bromige",
    price: "$7.99",
    imageUrl: "../Imgs/Books/ (47).jpg",
    author: "Iris Bromige",
    category: "Romance",
    availability: true,
    description:
      "Known for her gentle romances, Bromige delivers a story filled with emotional depth, exploring themes of love, loss, and resilience.",
  },
  {
    section: "Most Read",
    name: "Ever After",
    price: "$3.99",
    imageUrl: "../Imgs/Books/ (48).jpg",
    author: "Graham Swift",
    category: "Fiction",
    availability: false,
    description:
      "A compelling narrative blending history, memory, and family lore, delving into the complex relationships and enduring consequences of past actions.",
  },
  {
    section: "Most Read",
    name: "The Fire & The Gold",
    price: "$6.99",
    imageUrl: "../Imgs/Books/ (50).jpg",
    author: "Phyllis A. Whitney",
    category: "Fiction",
    availability: true,
    description:
      "A suspenseful novel that intertwines romance with mystery, set against the dramatic backdrop of a grand family mansion with dark secrets.",
  },
  {
    section: "Most Read",
    name: "An Offer From A Gentleman",
    price: "$9.99",
    imageUrl: "../Imgs/Books/ (51).jpg",
    author: "Julia Quinn",
    category: "Romance",
    availability: false,
    description:
      "This installment of the Bridgerton series is a Cinderella-like tale of love that transcends the barriers of social class and personal challenges.",
  },
  {
    section: "Most Read",
    name: "Creole Holiday",
    price: "$10.99",
    imageUrl: "../Imgs/Books/ (52).jpg",
    author: "Elisabeth Ogilvie",
    category: "Romance",
    availability: true,
    description:
      "A romance that captures the vibrant culture and scenic beauty of Creole life, intertwined with a story of love and discovery.",
  },
  {
    section: "Most Read",
    name: "El Feminisimo es para el mundo",
    price: "$11.99",
    imageUrl: "../Imgs/Books/ (53).jpg",
    author: "Bell Hooks",
    category: "Non-fiction",
    availability: false,
    description:
      "An insightful exploration into feminism, addressing how it can be a powerful tool for global change and social justice.",
  },
  {
    section: "Most Read",
    name: "Atomic Habits",
    price: "$24.99",
    imageUrl: "../Imgs/Books/ (54).jpg",
    author: "James Clear",
    category: "Self Help",
    availability: true,
    description:
      "A transformative guide that offers strategies for forming good habits, breaking bad ones, and mastering the tiny behaviors that lead to remarkable results.",
  },
  {
    section: "Most Read",
    name: "Think & Grow Rich",
    price: "$24.99",
    imageUrl: "../Imgs/Books/ (55).jpg",
    author: "Napoleon Hill",
    category: "Self Help",
    availability: false,
    description:
      "A classic in personal development and self-help, providing effective principles for achieving personal and financial success.",
  },
  {
    section: "Most Read",
    name: "The Rebel",
    price: "$29.99",
    imageUrl: "../Imgs/Books/ (56).jpg",
    author: "Albert Camus",
    category: "Philosophy",
    availability: true,
    description:
      "An in-depth philosophical exploration of rebellion and its implications on modern society, offering a profound discussion on freedom and justice.",
  },
  {
    section: "Most Read",
    name: "Wuthering Heights",
    price: "$31.99",
    imageUrl: "../Imgs/Books/ (57).jpg",
    author: "Emily Bronte",
    category: "Classic Literature",
    availability: false,
    description:
      "A classic novel that vividly portrays passionate and tumultuous relationships amidst the wild and rugged Yorkshire moors.",
  },
  {
    section: "None",
    name: "The Complete Works of William Shakespeare",
    price: "$21.99",
    imageUrl: "../Imgs/Books/(58).jpg",
    author: "William Shakespeare",
    category: "Classic Literature",
    availability: true,
    description:
      "An exhaustive collection of Shakespeare's plays, sonnets, and poems, offering a comprehensive view of his profound genius in English literature.",
  },
  {
    section: "Most Read",
    name: "The Catcher in the Rye",
    price: "$12.99",
    imageUrl: "../Imgs/Books/(59).jpg",
    author: "J.D. Salinger",
    category: "Classic Literature",
    availability: true,
    description:
      "A novel about teenage rebellion and alienation, following Holden Caulfield's experiences in New York City after being expelled from prep school.",
  },
  {
    section: "Sale",
    name: "1984",
    price: "$34.99",
    imageUrl: "../Imgs/Books/(60).jpg",
    author: "George Orwell",
    category: "Fiction",
    availability: false,
    description:
      "A dystopian novel that explores the dangers of totalitarianism, depicting a society under omnipresent government surveillance and public manipulation.",
  },
  {
    section: "Sale",
    name: "To Kill a Mockingbird",
    price: "$21.99",
    imageUrl: "../Imgs/Books/(61).jpg",
    author: "Harper Lee",
    category: "Classic Literature",
    availability: true,
    description:
      "A powerful novel that explores themes of racial injustice, moral growth, and the loss of innocence through the eyes of young Scout Finch.",
  },
  {
    section: "Sale",
    name: "The Great Gatsby",
    price: "$39.99",
    imageUrl: "../Imgs/Books/(62).jpg",
    author: "F. Scott Fitzgerald",
    category: "Classic Literature",
    availability: false,
    description:
      "A novel set in the Jazz Age that critiques the American Dream through the tragic story of Jay Gatsby's love for Daisy Buchanan.",
  },
  {
    section: "Sale",
    name: "Pride and Prejudice",
    price: "$12.99",
    imageUrl: "../Imgs/Books/(63).jpg",
    author: "Jane Austen",
    category: "Classic Literature",
    availability: true,
    description:
      "A witty and romantic novel that examines the societal expectations and romantic entanglements of the Bennet sisters in early 19th-century England.",
  },
  {
    section: "None",
    name: "Band of Brothers",
    price: "$23.99",
    imageUrl: "../Imgs/Books/(64).jpg",
    author: "Stephen E. Ambrose",
    category: "Military",
    availability: true,
    description:
      "Follows the story of Easy Company, 506th Regiment of the 101st Airborne Division, from their training in Georgia to the end of World War II.",
  },

  {
    section: "None",
    name: "The Things They Carried",
    price: "$43.99",
    imageUrl: "../Imgs/Books/(65).jpg",
    author: "Tim O'Brien",
    category: "Military",
    availability: true,
    description:
      "A collection of interconnected short stories about a platoon of American soldiers during the Vietnam War, exploring the emotional and psychological burdens they carry.",
  },
  {
    section: "Popular",
    name: "Steve Jobs",
    price: "$23.99",
    imageUrl: "../Imgs/Books/(66).jpg",
    author: "Walter Isaacson",
    category: "Biography",
    availability: true,
    description:
      "A comprehensive biography of Steve Jobs, co-founder of Apple Inc., offering insights into his life, personality, and innovative vision.",
  },

  {
    section: "None",
    name: "Becoming",
    price: "$21.99",
    imageUrl: "../Imgs/Books/(67).jpg",
    author: "Michelle Obama",
    category: "Biography",
    availability: true,
    description:
      "Memoir by Michelle Obama, the former First Lady of the United States, detailing her journey from childhood to the White House and beyond.",
  },
  {
    section: "Most Read",
    name: "Leonardo da Vinci",
    price: "$14.99",
    imageUrl: "../Imgs/Books/(69).jpg",
    author: "Walter Isaacson",
    category: "Biography",
    availability: true,
    description:
      "A biography of Leonardo da Vinci, one of the most creative and influential figures in human history, exploring his art, science, and genius.",
  },
  {
    section: "None",
    name: "The Diary of a Young Girl",
    price: "$8.99",
    imageUrl: "../Imgs/Books/(68).jpg",
    author: "Anne Frank",
    category: "Biography",
    availability: true,
    description:
      "The diary of Anne Frank, a Jewish girl hiding with her family during the Nazi occupation of the Netherlands, offering a poignant and powerful account of life during World War II.",
  },
  {
    section: "None",
    name: "Sapiens: A Brief History of Humankind",
    price: "$11.99",
    imageUrl: "../Imgs/Books/(70).jpg",
    author: "Yuval Noah Harari",
    category: "Non-fiction",
    availability: true,
    description:
      "Explores the history of Homo sapiens from the emergence of modern humans in Africa to the present day, covering key revolutions in human society and culture.",
  },

  {
    section: "None",
    name: "Educated",
    price: "$5.99",
    imageUrl: "../Imgs/Books/(71).jpg",
    author: "Tara Westover",
    category: "Non-fiction",
    availability: true,
    description:
      "Memoir recounting Tara Westover's upbringing in a strict Mormon household in rural Idaho, her quest for education, and her journey to break free from her past.",
  },

  {
    section: "None",
    name: "The Immortal Life of Henrietta Lacks",
    price: "$8.99",
    imageUrl: "../Imgs/Books/(72).jpg",
    author: "Rebecca Skloot",
    category: "Non-fiction",
    availability: true,
    description:
      "Tells the story of Henrietta Lacks, whose cells were taken without her consent in 1951 and became one of the most important cell lines in medical research, revolutionizing modern medicine.",
  },

  {
    section: "None",
    name: "The Power of Habit: Why We Do What We Do in Life and Business",
    price: "$11.99",
    imageUrl: "../Imgs/Books/(73).jpg",
    author: "Charles Duhigg",
    category: "Non-fiction",
    availability: true,
    description:
      "Examines the science behind habit formation and how habits shape our lives, offering insights into how habits can be changed to achieve personal and professional success.",
  },
  {
    section: "None",
    name: "The Elements of Style",
    price: "$9.99",
    imageUrl: "../Imgs/Books/(74).jpg",
    author: "William Strunk Jr. and E.B. White",
    category: "Educational",
    availability: true,
    description:
      "A classic guide to English language usage and style, offering timeless advice on writing clearly and effectively.",
  },

  {
    section: "None",
    name: "A Brief History of Time",
    price: "$12.99",
    imageUrl: "../Imgs/Books/(75).jpg",
    author: "Stephen Hawking",
    category: "Educational",
    availability: true,
    description:
      "Explores the origins, nature, and eventual fate of the universe, presenting complex scientific concepts in a clear and accessible manner.",
  },

  {
    section: "None",
    name: "Thinking, Fast and Slow",
    price: "$14.99",
    imageUrl: "../Imgs/Books/(76).jpg",
    author: "Daniel Kahneman",
    category: "Educational",
    availability: true,
    description:
      "Investigates the two systems that drive the way we think: the fast, intuitive System 1 and the slower, more deliberative System 2, offering insights into human decision-making.",
  },

  {
    section: "None",
    name: "The Selfish Gene",
    price: "$11.99",
    imageUrl: "../Imgs/Books/(77).jpg",
    author: "Richard Dawkins",
    category: "Educational",
    availability: true,
    description:
      "Explores the gene-centered view of evolution, arguing that genes are the primary unit of selection and explaining how selfish genes shape biological organisms and behavior.",
  },
  {
    section: "None",
    name: "The Name of the Wind",
    price: "$10.99",
    imageUrl: "../Imgs/Books/(78).jpg",
    author: "Patrick Rothfuss",
    category: "Fantasy",
    availability: true,
    description:
      "Follows the life of Kvothe, a magically gifted young man, as he grows to be the most notorious wizard his world has ever seen.",
  },

  {
    section: "None",
    name: "Mistborn: The Final Empire",
    price: "$12.99",
    imageUrl: "../Imgs/Books/(79).jpg",
    author: "Brandon Sanderson",
    category: "Fantasy",
    availability: true,
    description:
      "Set in a world where ash falls from the sky and mist dominates the night, follows a young thief as she discovers her extraordinary powers and joins a rebellion to overthrow a god-like tyrant.",
  },
  {
    section: "None",
    name: "Meditations",
    price: "$8.99",
    imageUrl: "../Imgs/Books/(80).jpg",
    author: "Marcus Aurelius",
    category: "Philosophy",
    availability: true,
    description:
      "A series of personal writings by Marcus Aurelius, Roman Emperor and Stoic philosopher, offering insights into Stoic philosophy and practical advice on how to live a meaningful life.",
  },
  {
    section: "None",
    name: "Thus Spoke Zarathustra",
    price: "$9.99",
    imageUrl: "../Imgs/Books/(81).jpg",
    author: "Friedrich Nietzsche",
    category: "Philosophy",
    availability: true,
    description:
      "Presents the philosophical ideas of Friedrich Nietzsche through the teachings of the fictional character Zarathustra, addressing themes of the death of God, the will to power, and the Übermensch.",
  },
  {
    section: "None",
    name: "Critique of Pure Reason",
    price: "$12.99",
    imageUrl: "../Imgs/Books/(82).jpg",
    author: "Immanuel Kant",
    category: "Philosophy",
    availability: true,
    description:
      "Explores the nature of human knowledge and the limits of reason, proposing that knowledge arises from the interaction between sensory experiences and innate concepts, thus revolutionizing modern philosophy.",
  },
  {
    section: "None",
    name: "The Waste Land",
    price: "$7.99",
    imageUrl: "../Imgs/Books/(83).jpg",
    author: "T.S. Eliot",
    category: "Poetry",
    availability: true,
    description:
      "A landmark modernist poem, exploring themes of disillusionment and despair in the aftermath of World War I, filled with allusions to mythology, literature, and religion.",
  },
  {
    section: "None",
    name: "Leaves of Grass",
    price: "$6.99",
    imageUrl: "../Imgs/Books/(84).jpg",
    author: "Walt Whitman",
    category: "Poetry",
    availability: true,
    description:
      "A collection of poems by Walt Whitman, celebrating the beauty of nature, the dignity of work, and the diversity of American life, considered one of the most important works in American literature.",
  },
  {
    section: "None",
    name: "The Girl with the Dragon Tattoo",
    price: "$9.99",
    imageUrl: "../Imgs/Books/(85).jpg",
    author: "Stieg Larsson",
    category: "Thriller",
    availability: true,
    description:
      "Follows journalist Mikael Blomkvist and hacker Lisbeth Salander as they investigate a decades-old disappearance and uncover dark secrets in Sweden's high society.",
  },

  {
    section: "None",
    name: "Gone Girl",
    price: "$10.99",
    imageUrl: "../Imgs/Books/(86).jpg",
    author: "Gillian Flynn",
    category: "Thriller",
    availability: true,
    description:
      "A gripping psychological thriller about a husband's search for his missing wife, revealing secrets and twists that keep readers on the edge of their seats.",
  },

  {
    section: "None",
    name: "The Da Vinci Code",
    price: "$11.99",
    imageUrl: "../Imgs/Books/(87).jpg",
    author: "Dan Brown",
    category: "Thriller",
    availability: true,
    description:
      "A fast-paced thriller that follows symbologist Robert Langdon and cryptologist Sophie Neveu as they unravel a conspiracy involving the Catholic Church and the mysterious secrets of the Holy Grail.",
  },
  {
    section: "None",
    name: "The Emperor of All Maladies: A Biography of Cancer",
    price: "$13.99",
    imageUrl: "../Imgs/Books/(88).jpg",
    author: "Siddhartha Mukherjee",
    category: "Medical",
    availability: true,
    description:
      "Traces the history of cancer from its first documented appearances thousands of years ago to the epic battles in the 20th century to cure, control, and conquer it, offering a fascinating insight into the disease and its treatment.",
  },

  {
    section: "None",
    name: "Being Mortal: Medicine and What Matters in the End",
    price: "$12.99",
    imageUrl: "../Imgs/Books/(89).jpg",
    author: "Atul Gawande",
    category: "Medical",
    availability: true,
    description:
      "Explores the intersection of aging, death, and medicine, challenging conventional notions of healthcare and offering insight into how we can live well even in the face of mortality.",
  },
  {
    section: "None",
    name: "A People's History of the United States",
    price: "$14.99",
    imageUrl: "../Imgs/Books/(90).jpg",
    author: "Howard Zinn",
    category: "History",
    availability: true,
    description:
      "Presents American history from the perspective of marginalized groups, including Native Americans, African Americans, and women, offering a critical analysis of traditional historical narratives.",
  },

  {
    section: "None",
    name: "The Rise and Fall of the Third Reich: A History of Nazi Germany",
    price: "$16.99",
    imageUrl: "../Imgs/Books/(91).jpg",
    author: "William L. Shirer",
    category: "History",
    availability: true,
    description:
      "A comprehensive account of the history of Nazi Germany, from Hitler's rise to power to the collapse of the Third Reich, providing insights into the key events and personalities of this tumultuous period.",
  },
];

// { TEMPLATE
//     section: "",
//     name: "",
//     price: "$",
//     imageUrl: "",
//     author: "",
//     category: "",
//     availability: true or false,
//     description: ""
//   },
