export const library = [
  {
    section: "Popular",
    name: "The Art Of War",
    price: "$69.99",
    imageUrl: "../Imgs/Books/ (1).jpg",
    author: "Sun Tzu",
    category: "Military",
    availability: true,
  },
  {
    section: "Popular",
    name: "Master Techniques in Surgery",
    price: "$62.99",
    imageUrl: "../Imgs/Books/ (2).jpg",
    author: "Various",
    category: "Medical",
    availability: false,
  },
  {
    section: "Popular",
    name: "The Banker's Wife",
    price: "$79.99",
    imageUrl: "../Imgs/Books/ (3).jpg",
    author: "Cristina Alger",
    category: "Thriller",
    availability: true,
  },
  {
    section: "Popular",
    name: "The Edge of the Sea",
    price: "$69.99",
    imageUrl: "../Imgs/Books/ (4).jpg",
    author: "Rachel Carson",
    category: "Nature",
    availability: false,
  },
  {
    section: "Popular",
    name: "The Subtle Art of not giving a fuck",
    price: "$99.99",
    imageUrl: "../Imgs/Books/ (5).jpg",
    author: "Mark Manson",
    category: "Self Help",
    availability: true,
  },
  {
    section: "Popular",
    name: "The Ebb Tide",
    price: "$74.99",
    imageUrl: "../Imgs/Books/ (6).jpg",
    author: "Beverly Lewis",
    category: "Fiction",
    availability: false,
  },
  {
    section: "Popular",
    name: "On the way to the Wedding",
    price: "$78.99",
    imageUrl: "../Imgs/Books/ (7).jpg",
    author: "Julia Quinn",
    category: "Romance",
    availability: true,
  },
  {
    section: "Popular",
    name: "Jets!Jets!Jets!",
    price: "$59.99",
    imageUrl: "../Imgs/Books/ (8).jpg",
    author: "Peter March",
    category: "Technology",
    availability: false,
  },
  {
    section: "Popular",
    name: "Libraries of The Future",
    price: "$49.99",
    imageUrl: "../Imgs/Books/ (9).jpg",
    author: "Leland M. Smith",
    category: "Technology",
    availability: true,
  },
  {
    section: "Popular",
    name: "Elon Musk",
    price: "$39.99",
    imageUrl: "../Imgs/Books/ (10).jpg",
    author: "Ashlee Vance",
    category: "Biography",
    availability: false,
  },
  {
    section: "Popular",
    name: "Lord of the Flies",
    price: "$29.99",
    imageUrl: "../Imgs/Books/ (11).jpg",
    author: "William Golding",
    category: "Fiction",
    availability: true,
  },
  {
    section: "Popular",
    name: "The Leaf",
    price: "$19.99",
    imageUrl: "../Imgs/Books/ (12).jpg",
    author: "Niggle",
    category: "Fiction",
    availability: false,
  },
  {
    section: "Popular",
    name: "The secret Language Of Birthdays",
    price: "$89.99",
    imageUrl: "../Imgs/Books/ (13).jpg",
    author: "Gary Goldschneider",
    category: "Astrology",
    availability: true,
  },
  {
    section: "Popular",
    name: "Red White Royal Blue",
    price: "$69.99",
    imageUrl: "../Imgs/Books/ (14).jpg",
    author: "Casey McQuiston",
    category: "Romance",
    availability: false,
  },
  {
    section: "Popular",
    name: "Game Of Thrones",
    price: "$75.99",
    imageUrl: "../Imgs/Books/ (15).jpg",
    author: "George R. R. Martin",
    category: "Fantasy",
    availability: true,
  },
  {
    section: "Popular",
    name: "Nothing",
    price: "$110.99",
    imageUrl: "../Imgs/Books/ (16).jpg",
    author: "Janne Teller",
    category: "Philosophical Fiction",
    availability: false,
  },
  {
    section: "Popular",
    name: "Snapdragon",
    price: "$9.99",
    imageUrl: "../Imgs/Books/ (17).jpg",
    author: "Kat Leyh",
    category: "Graphic Novel",
    availability: true,
  },
  {
    section: "Popular",
    name: "Working On Mars",
    price: "$39.99",
    imageUrl: "../Imgs/Books/ (18).jpg",
    author: "William K. Hartmann",
    category: "Science",
    availability: false,
  },
  {
    section: "Popular",
    name: "Harry Potter",
    price: "$4.99",
    imageUrl: "../Imgs/Books/ (19).jpg",
    author: "J.K. Rowling",
    category: "Fantasy",
    availability: true,
  },
  {
    section: "Sale",
    name: "The Duke and I",
    price: "$70.99",
    imageUrl: "../Imgs/Books/ (20).jpg",
    author: "Julia Quinn",
    category: "Romance",
    availability: false,
  },
  {
    section: "Sale",
    name: "Historia Czasu",
    price: "$49.99",
    imageUrl: "../Imgs/Books/ (21).jpg",
    author: "Stephen Hawking",
    category: "Science",
    availability: true,
  },
  {
    section: "Sale",
    name: "Nothing Part.2",
    price: "$89.99",
    imageUrl: "../Imgs/Books/ (22).jpg",
    author: "Janne Teller",
    category: "Philosophical Fiction",
    availability: false,
  },
  {
    section: "Sale",
    name: "Artie And The WolfMoon",
    price: "$87.99",
    imageUrl: "../Imgs/Books/ (23).jpg",
    author: "Olivia Stephens",
    category: "Graphic Novel",
    availability: true,
  },
  {
    section: "Sale",
    name: "Read People Like A Book",
    price: "$3.99",
    imageUrl: "../Imgs/Books/ (24).jpg",
    author: "Patrick King",
    category: "Psychology",
    availability: false,
  },
  {
    section: "Sale",
    name: "Control Your Mind",
    price: "$44.99",
    imageUrl: "../Imgs/Books/ (25).jpg",
    author: "Various Authors",
    category: "Self Help",
    availability: true,
  },
  {
    section: "Sale",
    name: "Landing Beaches",
    price: "$29.99",
    imageUrl: "../Imgs/Books/ (27).jpg",
    author: "George Forty",
    category: "History",
    availability: false,
  },
  {
    section: "Sale",
    name: "Fifty Shades Of Grey",
    price: "$149.99",
    imageUrl: "../Imgs/Books/ (28).jpg",
    author: "E.L. James",
    category: "Romance",
    availability: true,
  },
  {
    section: "Sale",
    name: "Romancing Mister Bridgerton",
    price: "$39.99",
    imageUrl: "../Imgs/Books/ (29).jpg",
    author: "Julia Quinn",
    category: "Romance",
    availability: false,
  },
  {
    section: "Sale",
    name: "Don't Believe Everything You Think",
    price: "$34.99",
    imageUrl: "../Imgs/Books/ (30).jpg",
    author: "Joseph Nguyen",
    category: "Self Help",
    availability: true,
  },
  {
    section: "Sale",
    name: "Encounter At Alpenrose",
    price: "$23.99",
    imageUrl: "../Imgs/Books/ (31).jpg",
    author: "Anonymous",
    category: "Fiction",
    availability: false,
  },
  {
    section: "Sale",
    name: "A Sir Philip con amor",
    price: "$87.99",
    imageUrl: "../Imgs/Books/ (32).jpg",
    author: "Julia Quinn",
    category: "Romance",
    availability: true,
  },
  {
    section: "Sale",
    name: "Yours Truly",
    price: "$56.99",
    imageUrl: "../Imgs/Books/ (33).jpg",
    author: "Kirsty Greenwood",
    category: "Romance",
    availability: false,
  },
  {
    section: "Sale",
    name: "Ansiedade",
    price: "$52.99",
    imageUrl: "../Imgs/Books/ (34).jpg",
    author: "Augusto Cury",
    category: "Self Help",
    availability: true,
  },
  {
    section: "Sale",
    name: "Jee Main",
    price: "$52.99",
    imageUrl: "../Imgs/Books/ (35).jpg",
    author: "Various Authors",
    category: "Educational",
    availability: false,
  },
  {
    section: "Sale",
    name: "Introduction To Google Analytics",
    price: "$52.99",
    imageUrl: "../Imgs/Books/ (38).jpg",
    author: "Justin Cutroni",
    category: "Technology",
    availability: true,
  },
  {
    section: "Most Read",
    name: "A Gentle Reminder",
    price: "$69.99",
    imageUrl: "../Imgs/Books/ (39).jpg",
    author: "Bianca Sparacino",
    category: "Poetry",
    availability: true,
  },
  {
    section: "Most Read",
    name: "Emperor Of Rome",
    price: "$95.99",
    imageUrl: "../Imgs/Books/ (40).jpg",
    author: "Robert Fabbri",
    category: "Historical Fiction",
    availability: false,
  },
  {
    section: "Most Read",
    name: "Castle in Corsica",
    price: "$45.99",
    imageUrl: "../Imgs/Books/ (41).jpg",
    author: "Margery Sharp",
    category: "Fiction",
    availability: true,
  },
  {
    section: "Most Read",
    name: "Stop Pretending",
    price: "$99.99",
    imageUrl: "../Imgs/Books/ (42).jpg",
    author: "Sonya Sones",
    category: "Young Adult",
    availability: false,
  },
  {
    section: "Most Read",
    name: "Nothing Part.3",
    price: "$0.99",
    imageUrl: "../Imgs/Books/ (43).jpg",
    author: "Janne Teller",
    category: "Philosophical Fiction",
    availability: true,
  },
  {
    section: "Most Read",
    name: "The Highest Dream",
    price: "$68.99",
    imageUrl: "../Imgs/Books/ (44).jpg",
    author: "Monica Sanz",
    category: "Romance",
    availability: false,
  },
  {
    section: "Most Read",
    name: "psychocybernetics",
    price: "$199.99",
    imageUrl: "../Imgs/Books/ (45).jpg",
    author: "Maxwell Maltz",
    category: "Self Help",
    availability: true,
  },
  {
    section: "Most Read",
    name: "Skye Cameron",
    price: "$90.99",
    imageUrl: "../Imgs/Books/ (46).jpg",
    author: "Phyllis A. Whitney",
    category: "Romance",
    availability: false,
  },
  {
    section: "Most Read",
    name: "Iris Bromige",
    price: "$67.99",
    imageUrl: "../Imgs/Books/ (47).jpg",
    author: "Iris Bromige",
    category: "Romance",
    availability: true,
  },
  {
    section: "Most Read",
    name: "Ever After",
    price: "$53.99",
    imageUrl: "../Imgs/Books/ (48).jpg",
    author: "Graham Swift",
    category: "Fiction",
    availability: false,
  },
  {
    section: "Most Read",
    name: "The Fire & The Gold",
    price: "$76.99",
    imageUrl: "../Imgs/Books/ (50).jpg",
    author: "Phyllis A. Whitney",
    category: "Fiction",
    availability: true,
  },
  {
    section: "Most Read",
    name: "An Offer From A Gentleman",
    price: "$69.99",
    imageUrl: "../Imgs/Books/ (51).jpg",
    author: "Julia Quinn",
    category: "Romance",
    availability: false,
  },
  {
    section: "Most Read",
    name: "Creole Holiday",
    price: "$70.99",
    imageUrl: "../Imgs/Books/ (52).jpg",
    author: "Elisabeth Ogilvie",
    category: "Romance",
    availability: true,
  },
  {
    section: "Most Read",
    name: "El Feminisimo es para el mundo",
    price: "$61.99",
    imageUrl: "../Imgs/Books/ (53).jpg",
    author: "Bell Hooks",
    category: "Non-fiction",
    availability: false,
  },
  {
    section: "Most Read",
    name: "Atomic Habits",
    price: "$60.99",
    imageUrl: "../Imgs/Books/ (54).jpg",
    author: "James Clear",
    category: "Self Help",
    availability: true,
  },
  {
    section: "Most Read",
    name: "Think & Grow Rich",
    price: "$69.99",
    imageUrl: "../Imgs/Books/ (55).jpg",
    author: "Napoleon Hill",
    category: "Self Help",
    availability: false,
  },
  {
    section: "Most Read",
    name: "The Rebel",
    price: "$299.99",
    imageUrl: "../Imgs/Books/ (56).jpg",
    author: "Albert Camus",
    category: "Philosophy",
    availability: true,
  },
  {
    section: "Most Read",
    name: "Wuthering Heights",
    price: "$79.99",
    imageUrl: "../Imgs/Books/ (57).jpg",
    author: "Emily Bronte",
    category: "Classic Literature",
    availability: false,
  },
];
